name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias UI
        working-directory: ui
        run: npm install
      - name: Compilar UI
        working-directory: ui
        run: npm run build
      - name: Instalar dependencias Rust
        run: cargo fetch
      - name: Construir paquete Tauri
        run: cargo tauri build --target x86_64-pc-windows-msvc
      - name: Subir artefactos
        uses: actions/upload-artifact@v4
        with:
          name: reader-windows
          path: src-tauri/target/x86_64-pc-windows-msvc/release/bundle
